global:
  scrape_interval: 5s  # Как часто собирать метрики

scrape_configs:
  - job_name: 'router1'
    static_configs:
      - targets: [ 'localhost:5020' ]  # Адрес вашего приложения FastAPI
  - job_name: 'router2'
    static_configs:
        - targets: [ 'localhost:5021' ]

